### ISSUE TITLE
feat: download file

### ISSUE THREAD

**Issue by shoriwe** [hawks-atlanta/worker-java#11]
## Tasks

- [ ] Create the struct in [RMI](https://github.com/hawks-atlanta/rmi-java) repository
- [ ] Update the gateway [dev](https://github.com/hawks-atlanta/gateway-java/tree/dev) branch
- [ ] Implement the service [worker](https://github.com/hawks-atlanta/worker-java)

## Ideas

```
struct download {
     string uuid;
}
```
